### ISSUE TITLE
After creating project for IAR\Keil HID became standart STM32 Human interface

### ISSUE THREAD

**Issue by mihannnik** [soonuse/stm32_joystick_for_nintendo_switch#1]
After more then 7 attempts сreate project with normal HID i just want to say, that i cant do it. 
Can you add EWARM\MDK project to repo? I just try to modify it to physical switches without UART control. 
I add .hex made in Keil. Also NS cant use it controller, but it work nice with release .hex file.
[stm32_joystick_for_nintendo_switch.zip](https://github.com/soonuse/stm32_joystick_for_nintendo_switch/files/6091335/stm32_joystick_for_nintendo_switch.zip)

**Comment by soonuse** [comment]
Some files will be replaced by STM32CubeMX. Please pay attention to them: usbd_core.c/usbd_def.h/usbd_hid.c/usbd_hid.h

**Comment by mihannnik** [comment]
After changes HID to CustomHID in CubeMX and copy with replace all from release it cant compile. 
In file usbd_customhid.c:
![image](https://user-images.githubusercontent.com/48869235/110507551-efae1800-8121-11eb-8c0d-f9449d4099c7.png)

**Comment by soonuse** [comment]
There is no need to copy all of them except for the USB descriptor and the config. See the struct USBD_HID_CfgDesc and HID_CUSTOM_ReportDesc, which are enough to build an HID device like Switch gamepad. The other parts are closely related to code generated from CubeMX, so I'm not sure if there is a certain difference.
